.PHONY: run-java-gate run-java-consumer kill-java build-java rundotnet publishdotnet fire pull

MAXRPS=1000
TESTDUR=1200
EVENTSIZE=10
GATEPORT=8888
LANG=Java
REV=$(shell git rev-parse --short HEAD)

JAVA_COMMON_PARAMS = -Xms16g -Xmx16g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -jar ./target/uber-kload-1.0-SNAPSHOT.jar

run-java-gate: kill-java build-java
	java ${JAVA_COMMON_PARAMS} gate

run-java-consumer: kill-java build-java
	java ${JAVA_COMMON_PARAMS} consumer

kill-java:
	pgrep java | awk '{system("kill -9 "$1)}'

build-java: pull
	mvn clean package

rundotnet: publishdotnet
	dotnet/KafkaLoadService.Core/bin/Debug/netcoreapp2.0/rhel-x64/publish/KafkaLoadService.Core

publishdotnet: pull
	cd dotnet/KafkaLoadService.Core && dotnet publish -r rhel-x64
	cp /usr/local/lib/librdkafka*.so dotnet/KafkaLoadService.Core/bin/Debug/netcoreapp2.0/rhel-x64/publish/

fire: pull
	echo "[phantom]"                                                                              >  autogenerated.ini
	echo "address = edi18:${GATEPORT}"                                                            >> autogenerated.ini
	echo "rps_schedule = line(1, ${MAXRPS}, 60s) const(${MAXRPS}, ${TESTDUR}s)"                   >> autogenerated.ini
	echo "instances = 10000"                                                                      >> autogenerated.ini
	echo "header_http = 1.1"                                                                      >> autogenerated.ini
	echo "headers = [Host: edi18]"                                                                >> autogenerated.ini
	echo "uris = /kload${EVENTSIZE}"                                                              >> autogenerated.ini
	echo "[telegraf]"                                                                             >> autogenerated.ini
	echo "config = monitoring.xml"                                                                >> autogenerated.ini
	echo "[overload]"                                                                             >> autogenerated.ini
	echo "token_file = token.txt"                                                                 >> autogenerated.ini
	echo "ver = ${REV}"                                                                           >> autogenerated.ini
	echo "job_name = Airlock-${LANG} /kload${EVENTSIZE} version ${REV}"                           >> autogenerated.ini
	echo "job_dsc = line(1, ${MAXRPS}, 60s) const(${MAXRPS}, ${TESTDUR}s)"                        >> autogenerated.ini
	echo "<Monitoring>"                                                                           >  monitoring.xml
	for host in edi18 icat-test01 icat-test02 icat-test03 ; do \
		echo "  <Host address=\"$$host\" comment=\"$$host\">"                                     >> monitoring.xml ; \
		echo "    <CPU />"                                                                        >> monitoring.xml ; \
		echo "    <Memory />"                                                                     >> monitoring.xml ; \
		echo "    <Disk devices='[\"sda3\",\"sda4\"]'></Disk>"                                    >> monitoring.xml ; \
		echo "    <Net interfaces='[\"team0\"]'></Net>"                                           >> monitoring.xml ; \
		echo "    <Netstat />"                                                                    >> monitoring.xml ; \
		echo "  </Host>"                                                                          >> monitoring.xml ; \
	done
	echo "</Monitoring>"                                                                          >> monitoring.xml
	yandex-tank -c autogenerated.ini

pull:
	git pull
