.PHONY: run build pull fire

MAXRPS=1000
TESTDUR=1200
EVENTSIZE=10
REV=$(shell git rev-parse HEAD)

run: build
	java -Xms16g -Xmx16g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -jar ./target/uber-kload-1.0-SNAPSHOT.jar

build: pull
	mvn clean package

fire: pull
	echo "[phantom]"                                                                              >  autogenerated.ini
	echo "address = edi18:8888"                                                                   >> autogenerated.ini
	echo "rps_schedule = line(1, ${MAXRPS}, 60s) const(${MAXRPS}, ${TESTDUR}s)"                   >> autogenerated.ini
	echo "instances = 10000"                                                                      >> autogenerated.ini
	echo "header_http = 1.1"                                                                      >> autogenerated.ini
	echo "uris = /kload${EVENTSIZE}"                                                              >> autogenerated.ini
	echo "[telegraf]"                                                                             >> autogenerated.ini
	echo "config = monitoring.xml"                                                                >> autogenerated.ini
	echo "[overload]"                                                                             >> autogenerated.ini
	echo "token_file = token.txt"                                                                 >> autogenerated.ini
	echo "job_name = Vostok ${REV}"                                                               >> autogenerated.ini
	echo "job_dsc = line(1, ${MAXRPS}, 60s) const(${MAXRPS}, ${TESTDUR}s) /kload${EVENTSIZE}"     >> autogenerated.ini
	echo "[sapsan]"                                                                               >> autogenerated.ini
	echo "project = Vostok"                                                                       >> autogenerated.ini
	echo "test_title = ${REV}"                                                                    >> autogenerated.ini
	echo "description = line(1, ${MAXRPS}, 60s) const(${MAXRPS}, ${TESTDUR}s) /kload${EVENTSIZE}" >> autogenerated.ini
	echo "<Monitoring>"                                                                           >  monitoring.xml
	for host in edi18 icat-test01 icat-test02 icat-test03 ; do \
		echo "  <Host address=\"$$host\">"                                                        >> monitoring.xml ; \
		echo "    <CPU />"                                                                        >> monitoring.xml ; \
		echo "    <Kernel />"                                                                     >> monitoring.xml ; \
		echo "    <System />"                                                                     >> monitoring.xml ; \
		echo "    <Memory />"                                                                     >> monitoring.xml ; \
		echo "    <Disk />"                                                                       >> monitoring.xml ; \
		echo "    <Net />"                                                                        >> monitoring.xml ; \
		echo "    <Netstat />"                                                                    >> monitoring.xml ; \
		echo "  </Host>"                                                                          >> monitoring.xml ; \
	done
	echo "</Monitoring>"                                                                          >> monitoring.xml
	yandex-tank -c autogenerated.ini

pull:
	git pull
